[package]
name = "sanity-rs"
description = "Porting @sanity/client in Rust"
keywords = ["sanity"]
version = "0.1.0"
edition = "2024"
autoexamples = false
exclude = ["./examples/"]
license = "MIT OR Apache-2.0"
authors = ["Riley1101"]
documentation = "https://github.com/Riley1101/sanity-rs"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0.215", features = ["derive"] }
thiserror = "2.0.3"
url = "2.5.4"
reqwest = { version = "0.12.9", features = ["json"] }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
dotenv = "0.15.0"

[lib]
name = "sanity_rs"           # The name of the target.
path = "src/lib.rs"    # The source file of the target.
test = true            # Is tested by default.
doctest = true         # Documentation examples are tested by default.
bench = true           # Is benchmarked by default.
doc = true             # Is documented by default.
proc-macro = false     # Set to `true` for a proc-macro library.
harness = true         # Use libtest harness.
edition = "2024"       # The edition of the target.
crate-type = ["lib"]   # The crate types to generate.
required-features = [] # Features required to build this target (N/A for lib).
