[package]
name = "leptos-example"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
leptos = { version = "0.7.0", features = ["csr"] }
serde = { version = "1.0.215", features = ["derive"] }
sanity-rs = { path = "../../" }
codee = "0.2.0"
